config/routes.rb
Rails.application.routes.draw do
  root 'films#index'
  resources :films
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:title, :Description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_with(model: film, local: true) do |form| %>
  <% if film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :Description %>
    <%= form.text_field :Description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Films</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film.title %></td>
        <td><%= film.Description %></td>
        <td><%= link_to 'Show', film %></td>
        <td><%= link_to 'Edit', edit_film_path(film) %></td>
        <td><%= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Film', new_film_path %>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @film.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @film.Description %>
</p>

<%= link_to 'Edit', edit_film_path(@film) %> |
<%= link_to 'Back', films_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFilm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>